Remove error response body transformation
sprockets/sprockets.mixins.http pull request #21
Opened 2019-08-29 17:39 UTC by nvllsvm

This feature prevents users from accessing other attributes in deserialized error response bodies.

2019-08-29 17:56 UTC, noone234 requested changes
This PR solves my problem. It exposes the original error response body.

2019-08-29 17:57 UTC, noone234 commented on sprockets/mixins/http/__init__.py
> -    def _error_message(self):
Would it help to keep this function definition, even though the function's no longer used?

2019-08-30 14:01 UTC, nvllsvm commented
@gmr Requesting your review as you initially introduced this feature.

2019-08-30 17:35 UTC, nvllsvm commented on sprockets/mixins/http/__init__.py
> -    def _error_message(self):
I'd rather not as it's too opinionated.

2019-10-28 14:07 UTC, gmr requested changes
I'd prefer to deprecate behaviors and allow for an override mechanic instead of remove/change them wholesale. This is a big enough behavior change that people should be aware of it and am concerned about pinning with the behavior change.

2019-11-14 16:57 UTC, nvllsvm commented
Closing in favor of @noone234 's work https://github.com/sprockets/sprockets.mixins.http/pull/25

2019-11-14 16:57 UTC, closed without merging